### ISSUE TITLE
Bert-VITS2  Korean version

### ISSUE THREAD

**Issue by Colinsnow1** [0913ktg/vits_korean_multispeaker#1]
Hello DaegyeomKim,

I am also  trying to training a Korean version of Bert-VITS2. Have you training the Korean models successfully?

Thank you for sharing your excellent code. Have a great day.

Best regards.

**Comment by 0913ktg** [comment]
Hello liuyangwen.

I'm currently pausing work on the Bert-VITS2 project. Based on my assessment of the fishaudio repository, it seemed challenging to train a Korean model there. Therefore, I am exploring methods with other VITS-based models using Korean data.

At the moment, I'm researching a VITS-based zero-shot multi-speaker Korean TTS model. If this model is successfully trained, I plan to incorporate BERT into it to ultimately create a BERT-VITS2 Korean model.

Thank you.

**Comment by Colinsnow1** [comment]
Dear DaegyeomKim,

I hope you are having a wonderful day.
Thank you for your reply and wish you success in training！

Best regards.
