### ISSUE TITLE
22kHz sampling rate 변환 문의

### ISSUE THREAD

**Issue by MingyuKim-2933** [0913ktg/vits_korean_multispeaker#2]
안녕하십니까, 음성 합성과 관련해 연구하고 있는 김민규입니다.

데이터 전처리 시 .wav 파일들의 samplling rate를 22kHz로 변환하라고 하셨는데
AI Hub의 데이터들의 sampling rate를 어떻게 변환하셨는지 알려주실 수 있으실까요?

감사합니다.

**Comment by 0913ktg** [comment]
안녕하세요 MingyuKim-2933님.

저는 우분투 환경에서 ffmpeg를 사용하여 wav 파일들을 resample 하였습니다. 
resample 하는 코드는 인터넷 검색 또는 chatgpt에 검색하면 작업 경로에 맞게 손쉽게 구현할 수 있을것으로 생각됩니다. 

감사합니다.

**Comment by MingyuKim-2933** [comment]
친절하고 꼼꼼하게 답변 해주셔서 감사드립니다!
